### ISSUE TITLE
Incorrect reordering of TimeSeries in degPattern

### ISSUE THREAD

**Issue by sum732** [lpantano/DEGreport#26]
Dear Team,
I am using degPatten to cluster and observe the changes across different time points. 
The command used is:

`res <- degPatterns(ma, design, time = "Age")`

design is as follows: 

  | Age | sizeFactor
-- | -- | --
Sample_41 | 6M | 0.6995291
Sample_42 | 6M | 1.4067538
Sample_44 | 6M | 0.7072592
Sample_45 | 12M | 0.8811723
Sample_46 | 12M | 0.9847001
Sample_47 | 12M | 0.7857639
Sample_48 | 18M | 1.1178253
Sample_49 | 18M | 1.1713206
Sample_50 | 18M | 1.2827632
Sample_51 | 18M | 1.4135661
Sample_52 | 21M | 1.2095196
Sample_53 | 21M | 0.8607367
Sample_54 | 21M | 1.0009709

The generated plot is here:
https://www.dropbox.com/s/52h2ryl90e4i5sz/degPatternTest.pdf?dl=0

In the design the time series is incremental i.e. "Age" is ascending. However, in the plot its shown as 12M, 18M, 21M, 6M. I want 6M,12M,18M,21M. How can I control the labelling? 

Thanks,
Sudeep

**Comment by lpantano** [comment]
Hi,

Thanks for the question!

Normally I define the factor before hand. So I will do:

design$Age = factor(design$Age, levels = c(“6M”, “12M”, “18M”, “21M”))


Let me know if that doesn’t solve the issue.

Cheers


On May 17, 2019 at 2:32:04 PM, sum732 (notifications@github.com) wrote:

Dear Team,
I am using degPatten to cluster and observe the changes across different
time points.
The command used is:

res <- degPatterns(ma, design, time = "Age")

design is as follows:
  Age sizeFactor
Sample_41 6M 0.6995291
Sample_42 6M 1.4067538
Sample_44 6M 0.7072592
Sample_45 12M 0.8811723
Sample_46 12M 0.9847001
Sample_47 12M 0.7857639
Sample_48 18M 1.1178253
Sample_49 18M 1.1713206
Sample_50 18M 1.2827632
Sample_51 18M 1.4135661
Sample_52 21M 1.2095196
Sample_53 21M 0.8607367
Sample_54 21M 1.0009709

The generated plot is here:
https://www.dropbox.com/s/52h2ryl90e4i5sz/degPatternTest.pdf?dl=0

In the design the time series is incremental i.e. "Age" is ascending.
However, in the plot its shown as 12M, 18M, 21M, 6M. I want 6M,12M,18M,21M.
How can I control the labelling?

Thanks,
Sudeep

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/lpantano/DEGreport/issues/26?email_source=notifications&email_token=AAML6HE5XKRLWKRAISU4KGLPV322JA5CNFSM4HNXPTBKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4GUOZSEQ>,
or mute the thread

**Comment by sum732** [comment]
It did the trick, thanks.
